/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package reactivos;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;


public class Login_frm extends javax.swing.JFrame {
int intentos = 0;
    /**
     * Creates new form Login_frm
     */
    public Login_frm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Title_lbl0 = new javax.swing.JLabel();
        Title_lbl1 = new javax.swing.JLabel();
        Title_lbl2 = new javax.swing.JLabel();
        Title_lbl3 = new javax.swing.JLabel();
        User_txt = new javax.swing.JTextField();
        Login_btn = new javax.swing.JButton();
        Pass_txt = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        Title_lbl0.setText("Texto de bienvenida");

        Title_lbl1.setText("Usuario:");

        Title_lbl2.setText("Contraseña:");

        Title_lbl3.setText("Login");

        Login_btn.setText("Entrar");
        Login_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Login_btnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(Title_lbl0)
                    .addComponent(Title_lbl1)
                    .addComponent(Title_lbl2)
                    .addComponent(Title_lbl3)
                    .addComponent(User_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Pass_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Login_btn))
                .addContainerGap(74, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Title_lbl0)
                .addGap(18, 18, 18)
                .addComponent(Title_lbl1)
                .addGap(9, 9, 9)
                .addComponent(User_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Title_lbl2)
                .addGap(18, 18, 18)
                .addComponent(Pass_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(Login_btn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Title_lbl3)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Login_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Login_btnMouseClicked
        if("".equals(this.User_txt.getText())){
            JOptionPane.showMessageDialog(null, "Por favor introduzca su usuario");
        }
        else {
        Connection conexion = null;
        Conectar conn = new Conectar();
        conn.setV_user("root");
        conn.setV_password("BuffaloSV503");
        conn.setV_server("localhost");
        conn.setV_db("biologia");
        conexion = conn.ConexionDB();
        String password = "";
        Statement stmt = null;
        String queryUser = "SELECT Login_Pass from login_table Where Login_ID_PK = '" + this.User_txt.getText() + "'";
        try{
            stmt = conexion.createStatement();
            ResultSet rs = stmt.executeQuery(queryUser);
            while(rs.next()){
                password = rs.getString("Login_Pass");
            }
        }
        catch(SQLException ex) {
            Logger.getLogger(Login_frm.class.getName()).log(Level.SEVERE, null, ex);
        }
        if (password.equals(String.valueOf(this.Pass_txt.getPassword()))){
            JOptionPane.showMessageDialog(null, "Acceso Concedido");
            Main_frm main = new Main_frm();
            main.Usuario = this.User_txt.getText();
            main.setVisible(true);
            main.setExtendedState(Main_frm.MAXIMIZED_BOTH);
            this.dispose();         
        }
        else {
            this.Title_lbl3.setText("Acceso Denegado");
        }
        
        if (intentos == 3)
        {
            JOptionPane.showMessageDialog(null, "Numero de intentos excedidos");
            this.dispose();
        }
        intentos++;
        }
    }//GEN-LAST:event_Login_btnMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        this.Title_lbl3.setText("");
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login_frm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login_frm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login_frm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login_frm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login_frm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Login_btn;
    private javax.swing.JPasswordField Pass_txt;
    private javax.swing.JLabel Title_lbl0;
    private javax.swing.JLabel Title_lbl1;
    private javax.swing.JLabel Title_lbl2;
    private javax.swing.JLabel Title_lbl3;
    private javax.swing.JTextField User_txt;
    // End of variables declaration//GEN-END:variables
}
